server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://192.168.0.17:5432/venda
    password: servidor123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
#logging:
#  level:
#    org.springframework.web.cors: DEBUG
#    org.springframework.web.servlet.DispatcherServlet: DEBUG