server:
  port: 0

spring:
  application:
    name: venda
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  profiles:
    active: lucas

